---
title: "Spray Charts"
author: "AA"
date: "9//2019"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
library(dplyr)
library(ggplot2)
```

```{r}
Deacons = read.csv('Wake4Ayush.csv')
head(Deacons)


Deacons %>%
  select(PitchCall, Direction, Distance) %>%
  head()

unique(Deacons$PitchCall)

Deacons_BIP = Deacons %>%
  filter(PitchCall == 'InPlay')

Deacons_BIP %>%
  select(PitchCall, Direction, Distance) %>%
  head()

summary(Deacons_BIP$Direction)
summary(Deacons_BIP$Distance)

Deacons_BIP$hc_x = tan((Deacons_BIP$Direction)*(pi/180)) * Deacons_BIP$Distance
Deacons_BIP$hc_y = Deacons_BIP$Distance


summary(Deacons_BIP$hc_x)
summary(Deacons_BIP$hc_y)

ggplot(Deacons_BIP, aes(x = hc_x, y = hc_y, color = PlayResult))+
  geom_point()


```

Adjust Name for updated Spray Charts:


```{r}
LC = subset(Deacons_BIP, Batter == 'Lanzilli, Chris')

colnames(LC)


LC %>%
  select(PitchCall, Direction, Distance) %>%
  head()

unique(LC$PitchCall)

LC_BIP = LC %>%
  filter(PitchCall == 'InPlay')

LC_BIP %>%
  select(PitchCall, Direction, Distance) %>%
  head()

summary(LC_BIP$hc_x)
summary(LC_BIP$hc_y)
```

```{r}
LC_R = subset(LC_BIP, PitcherThrows == 'Right')
LC_L = subset(LC_BIP, PitcherThrows == 'Left')

LC_R_FB = subset(LC_R, TaggedPitchType == 'Fastball')
LC_R_CB = subset(LC_R, TaggedPitchType == 'Curveball')
LC_R_SL = subset(LC_R, TaggedPitchType == 'Slider')
LC_R_CH = subset(LC_R, TaggedPitchType == 'ChangeUp')

LC_L_FB = subset(LC_L, TaggedPitchType == 'Fastball')
LC_L_CB = subset(LC_L, TaggedPitchType == 'Curveball')
LC_L_SL = subset(LC_L, TaggedPitchType == 'Slider')
LC_L_CH = subset(LC_L, TaggedPitchType == 'ChangeUp')

spray_chart = function(...){
  ggplot(...) + 
    geom_curve(x = -225, xend = 225, y = 310, yend = 300, curvature = -0.45) + 
    geom_segment(x = -225, xend = 0, y = 310, yend = 0) +
    geom_segment(x =  225, xend = 0, y = 300, yend = 0) + 
    geom_curve(x = -65, xend = 65, y = 95, yend = 95, curvature = -0.50, linetype = "dotted") +
    coord_fixed() +
    scale_x_continuous(NULL, limits = c(-300,300)) + 
    scale_y_continuous(NULL, limits = c(-25,500))
}

all_spray_chart = spray_chart(LC_BIP, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs All')


spray_chart = function(...){
  ggplot(...) + 
    geom_curve(x = -225, xend = 225, y = 310, yend = 300, curvature = -0.45) + 
    geom_segment(x = -225, xend = 0, y = 310, yend = 0) +
    geom_segment(x =  225, xend = 0, y = 300, yend = 0) + 
    geom_curve(x = -65, xend = 65, y = 95, yend = 95, curvature = -0.50, linetype = "dotted") +
    coord_fixed() +
    scale_x_continuous(NULL, limits = c(-300,300)) + 
    scale_y_continuous(NULL, limits = c(-25,500))
}
spray_chart_right = spray_chart(LC_R, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Right')

spray_chart = function(...){
  ggplot(...) + 
    geom_curve(x = -225, xend = 225, y = 310, yend = 300, curvature = -0.45) + 
    geom_segment(x = -225, xend = 0, y = 310, yend = 0) +
    geom_segment(x =  225, xend = 0, y = 300, yend = 0) + 
    geom_curve(x = -65, xend = 65, y = 95, yend = 95, curvature = -0.50, linetype = "dotted") +
    coord_fixed() +
    scale_x_continuous(NULL, limits = c(-300,300)) + 
    scale_y_continuous(NULL, limits = c(-25,500))
}

spray_chart_left = spray_chart(LC_L, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Left')

spray_chart_R_FB = spray_chart(LC_R_FB, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Righty Fastballs')

spray_chart_R_CB = spray_chart(LC_R_CB, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Righty Curveballs')

spray_chart_R_SL = spray_chart(LC_R_SL, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Righty Sliders')

spray_chart_R_CH = spray_chart(LC_R_CH, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Righty Changeups')

spray_chart_L_FB = spray_chart(LC_L_FB, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Lefty Fastballs')

spray_chart_L_CB = spray_chart(LC_L_CB, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Lefty Curveballs')

spray_chart_L_SL = spray_chart(LC_L_SL, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Lefty Sliders')

spray_chart_L_CH = spray_chart(LC_L_CH, aes(x = hc_x, y = hc_y, color = PlayResult)) +
  geom_point() +
  scale_color_hue()+
  ggtitle('Spray Chart vs Lefty Changeups')





all_spray_chart
spray_chart_right
spray_chart_left 
spray_chart_R_FB
spray_chart_R_CB
spray_chart_R_SL
spray_chart_R_CH
spray_chart_L_FB
spray_chart_L_CB
spray_chart_L_SL
spray_chart_L_CH

```

